version: '3.8'

services:
  db:
    build: .
    container_name: stackauth-db
    environment:
      POSTGRES_PASSWORD: postgres
      # Configurações básicas
      POSTGRES_MAX_CONNECTIONS: 100
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 768MB
      
      # Configurações de memória
      POSTGRES_WORK_MEM: 4MB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      
      # Configurações de WAL
      POSTGRES_WAL_BUFFERS: 16MB
      POSTGRES_MIN_WAL_SIZE: 1GB
      POSTGRES_MAX_WAL_SIZE: 4GB
      POSTGRES_WAL_LEVEL: logical
      
      # Configurações de paralelismo
      POSTGRES_MAX_WORKER_PROCESSES: 8
      POSTGRES_MAX_PARALLEL_WORKERS: 8
      POSTGRES_MAX_PARALLEL_WORKERS_PER_GATHER: 4
      POSTGRES_MAX_PARALLEL_MAINTENANCE_WORKERS: 4
      
      # Outras configurações
      POSTGRES_CHECKPOINT_COMPLETION_TARGET: 0.9
      POSTGRES_STATISTICS_TARGET: 100
      POSTGRES_RANDOM_PAGE_COST: 1.1
      POSTGRES_IO_CONCURRENCY: 200
      POSTGRES_AUTOVACUUM: "on"
      
      # Delay para desenvolvimento (opcional)
      # POSTGRES_DELAY_MS: 100
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: